  
SELECT TIME_TABLE.TITLE
	 , ORDERS.CATEGORY_NAME
	 , IFNULL(ORDERS.CNT,0)
 FROM (SELECT '09-10' AS TITLE UNION 
 	   SELECT '10-11' AS TITLE UNION
 	   SELECT '11-12' AS TITLE UNION
 	   SELECT '12-13' AS TITLE UNION
 	   SELECT '13-14' AS TITLE UNION
 	   SELECT '14-15' AS TITLE UNION
 	   SELECT '15-16' AS TITLE UNION
 	   SELECT '16-17' AS TITLE UNION
 	   SELECT '17-18' AS TITLE UNION
 	   SELECT '18-19' AS TITLE UNION
 	   SELECT '19-20' AS TITLE UNION
 	   SELECT '20-21' AS TITLE UNION
 	   SELECT '21-22' AS TITLE UNION
 	   SELECT '22-23' AS TITLE ) TIME_TABLE 	   
 LEFT OUTER JOIN (SELECT TITLE,CATEGORY_NAME, COUNT(*) AS CNT
 				    FROM (SELECT (CASE WHEN HOUR(ORDERS.CREATE_DT)>= '09' AND HOUR(ORDERS.CREATE_DT)<'10'
									    THEN '09-10'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '10' AND HOUR(ORDERS.CREATE_DT)<'11'
									    THEN '10-11'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '11' AND HOUR(ORDERS.CREATE_DT)<'12'
									    THEN '11-12'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '12' AND HOUR(ORDERS.CREATE_DT)<'13'
									    THEN '12-13'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '13' AND HOUR(ORDERS.CREATE_DT)<'14'
									    THEN '13-14'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '14' AND HOUR(ORDERS.CREATE_DT)<'15'
									    THEN '14-15'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '15' AND HOUR(ORDERS.CREATE_DT)<'16'
									    THEN '15-16'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '16' AND HOUR(ORDERS.CREATE_DT)<'17'
									    THEN '16-17'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '17' AND HOUR(ORDERS.CREATE_DT)<'18'
									    THEN '17-18'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '18' AND HOUR(ORDERS.CREATE_DT)<'19'
									    THEN '18-19'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '19' AND HOUR(ORDERS.CREATE_DT)<'20'
									    THEN '19-20'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '20' AND HOUR(ORDERS.CREATE_DT)<'21'
									    THEN '20-21'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '21' AND HOUR(ORDERS.CREATE_DT)<'22'
									    THEN '21-22'
									    WHEN HOUR(ORDERS.CREATE_DT)>= '22' AND HOUR(ORDERS.CREATE_DT)<'23'
									    THEN '22-23'
									    ELSE '' END ) AS TITLE ,
									    CTG.CATEGORY_NAME
							 FROM ORDERS
							INNER JOIN ITEM
							   ON ORDERS.ORDER_IDX = ITEM.ORDER_IDX
							INNER JOIN PRODUCT PROD
							   ON ITEM.PRODUCT = PROD.PRODUCT_CODE
							INNER JOIN CATEGORY CTG
							   ON PROD.CATEGORY_CODE = CTG.CATEGORY_CODE
							WHERE 1=1 
							  AND STORE='STORE-002'
							  AND DATE_SUB(NOW(), INTERVAL 1 MONTH) < ORDERS.CREATE_DT) ORDERS
				  GROUP BY ORDERS.TITLE, ORDERS.CATEGORY_NAME) ORDERS
   ON TIME_TABLE.TITLE = ORDERS.TITLE
   
   
SELECT PROD.PRODUCT_NAME, COUNT(*) AS CNT
FROM ORDERS
INNER JOIN ITEM
   ON ORDERS.ORDER_IDX = ITEM.ORDER_IDX
INNER JOIN PRODUCT PROD
   ON ITEM.PRODUCT = PROD.PRODUCT_CODE
INNER JOIN CATEGORY CTG
   ON PROD.CATEGORY_CODE = CTG.CATEGORY_CODE
  AND CTG.CATEGORY_NAME = "샌드위치"
WHERE 1=1 
  AND STORE='STORE-002'
  AND STATE != 'state-05'
  AND DATE_SUB(NOW(), INTERVAL 1 MONTH) < ORDERS.CREATE_DT
GROUP BY PROD.PRODUCT_NAME
ORDER BY CNT DESC

SELECT distinct item.product FROM ORDERS
INNER JOIN ITEM
   ON ORDERS.ORDER_IDX = ITEM.ORDER_IDX
WHERE 1=1 
  AND STORE='STORE-002'

SELECT USER_GROUP, COUNT(*) AS CNT
FROM(SELECT IF(CNT != 1 ,'REORDER','FIRST') AS 'USER_GROUP'
	 FROM (SELECT MID, COUNT(*) AS CNT
			 FROM ORDERS 
			WHERE 1=1
			  AND STORE = "STORE-001"
			  AND STATE != 'state-05'
			  AND DATE_SUB(NOW(), INTERVAL 1 MONTH) < ORDERS.CREATE_DT
			GROUP BY MID ) ORDERS  
	) ORDERS	
GROUP BY USER_GROUP	
ORDER BY USER_GROUP DESC


SELECT CONCAT(NAME,'(', FORMAT(SUM(TOTAL) , 0),')') AS MID
     , COUNT(*) AS CNT
 FROM ORDERS 
 INNER JOIN USER
 ON ORDERS.MID = USER.MID 
WHERE 1=1
  AND STORE = "STORE-001"
  AND STATE != 'state-05'
  AND DATE_SUB(NOW(), INTERVAL 1 MONTH) < ORDERS.CREATE_DT
GROUP BY ORDERS.MID
 ORDER BY CNT DESC;
 
 
 
 
SELECT USER_GROUP, COUNT(*) AS CNT
FROM(SELECT IF(CNT != 1 ,'REORDER','FIRST') AS 'USER_GROUP', COUNT(*) AS CNT
	 FROM (SELECT MID, COUNT(*) AS CNT
			 FROM ORDERS 
			WHERE 1=1
    	   	  AND STORE = 'STORE-001'
			  AND STATE != 'state-05'
			  AND DATE_SUB(NOW(), INTERVAL 1 MONTH) < ORDERS.CREATE_DT
			GROUP BY MID ) ORDERS  
			GROUP BY USER_GROUP
	) ORDERS	
	
ORDER BY USER_GROUP DESC


SELECT IF(CNT != 1 ,'REORDER','FIRST') AS 'USER_GROUP' , COUNT(*) AS CNT
  FROM (SELECT MID, COUNT(*) AS CNT
    	  FROM ORDERS 
   	  	 WHERE 1=1
   	  	   AND STORE = #{store}
   	  	   AND STATE != 'state-05'
    	   	  	   AND DATE_SUB(NOW(), INTERVAL 1 MONTH) <![CDATA[<]]> ORDERS.CREATE_DT
    	   	  	 GROUP BY MID ) ORDERS 
  	   	  GROUP BY USER_GROUP 
	      ORDER BY USER_GROUP DESC